export {
  type ParticleEmitterConfig,
  type ParticleEmitterState,
  type ParticlePool,
  type ParticleSystemState,
  type RangeValue,
  type RangeColor,
  type Curve,
  type CurveKeyframe,
  type ColorGradient,
  type ColorGradientStop,
  type BurstConfig,
  type BurstTracker,
  type ShapeConfig,
  type ShapePointConfig,
  type ShapeCircleConfig,
  type ShapeRectangleConfig,
  SimulationSpace,
  EmitterShape,
  ParticleRenderMode,
  EmitterPlayState,
} from './particles.types.ts';

export {
  createParticleState,
  createEmitter,
  destroyEmitter,
  playEmitter,
  stopEmitter,
  pauseEmitter,
  resumeEmitter,
  resetEmitter,
  setEmitterPosition,
  updateEmitter,
  particleSystem,
  range,
  fixed,
  fixedColor,
  linear,
  constant,
} from './particles.ts';
